services:
  database:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      POSTGRES_DB: "toeic_z9tkvtu"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/toeic_z9tkvtu
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - database
    ports:
      - "8761:8761"


volumes:
  postgres_data: