spring:
  application:
    name: z9tkvtu
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://database:5432/toeic_z9tkvtu"
    username: "root"
    password: "123"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    jwt:
      key:
        access: Amx/EfkMnYwVMsFHooxnD2AeZPWvY5U2UD9HblsXV6E=
        refresh: 42xzvYLllE839NhwAjE+1F6bhgMN3lCuLX7xkHBmNaM=