spring:
  docker:
    compose:
      enabled: false
  application:
    name: z9tkvtu
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/toeic_z9tkvtu"
    username: "postgres"
    password: "Namcam"
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

api:
  security:
    jwt:
      key:
        access: Amx/EfkMnYwVMsFHooxnD2AeZPWvY5U2UD9HblsXV6E=
        refresh: 42xzvYLllE839NhwAjE+1F6bhgMN3lCuLX7xkHBmNaM=

server:
  port: 8080