export const TEST_CONSTANTS = {
  SIMULATION_TEST: 100201,
  MINI_TEST: 100202,
  FULL_TEST: 100203,
};

export const QUESTION_TYPE = {
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
  IMAGE_BASED: "IMAGE_BASED",
  AUDIO_BASED: "AUDIO_BASED",
  FILL_IN_BLANK: "FILL_IN_BLANK",
};
