-- Insert data for PART 2 TOEIC no1
INSERT INTO public.question (part_id, grading_type, "content", "options", correct_answer, explanation, order_number) VALUES
(51, 'LISTENING','1', '{"A": "She is riding a moving walk.", "B": "She is pulling her luggage along.", "C": "She is packing her bags for a trip.", "D": "She is lining up at the check-in desk."}', 'B', NULL, 1),
(51, 'LISTENING','2', '{"A": "They’re enjoying the view.", "B": "They’re reviewing some documents.", "C": "They’re having a discussion.", "D": "They’re sitting in a circle."}', 'B', NULL, 2),
(51, 'LISTENING','3', '{"A": "He’s buying a newspaper.", "B": "He’s sending a text message.", "C": "He’s holding a publication.", "D": "He’s adjusting his tie."}', 'C', NULL, 3),
(51, 'LISTENING','4', '{"A": "The loaves are being taken out of the oven.", "B": "The loaves have been arranged on the shelves.", "C": "The loaves are being prepared by the baker.", "D": "The loaves have been displayed on the table."}', 'B', NULL, 4),
(51, 'LISTENING','5', '{"A": "The lighthouse is under construction.", "B": "The beach house is being tom down.", "C": "One structure is taller than the others.", "D": "There is a path through the field."}', 'C', NULL, 5),
(51, 'LISTENING','6', '{"A": "He’s making notes in his planner.", "B": "He’s typing on the keyboard.", "C": "He’s facing the monitor.", "D": "He’s turning the computer on."}', 'A', NULL, 6),
(51, 'LISTENING','7', '{"A": "All of the flowers are blooming.", "B": "There are trees along the path.", "C": "It’s snowing in the forest.", "D": "There are piles of logs on the road."}', 'A', NULL, 7),
(51, 'LISTENING','8', '{"A": "He’s entering a library.", "B": "She’s fixing a bookcase.", "C": "He’s indicating something on a page.", "D": "She’s turning the pages."}', 'C', NULL, 8),
(51, 'LISTENING','9', '{"A": "The lamps are being installed.", "B": "The windows have been left open.", "C": "The kitchen table is being set.", "D": "The chairs are placed around the table."}', 'C', NULL, 9),
(51, 'LISTENING','10', '{"A": "The people are meeting with a travel agent.", "B": "The people are boarding an airplane.", "C": "The people are waiting in a terminal.", "D": "The people are booking their flights."}', 'C', NULL, 10);

-- Insert data for PART 2 TOEIC no2
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(101, 'LISTENING','They’re discussing a document.', '{"A": "They’re copying some papers.", "B": "They’re discussing a document.", "C": "They’re writing a book.", "D": "They’re looking for a folder."}', 'B', NULL, 1),
(101, 'LISTENING','He’s working at his desk.', '{"A": "He’s eating lunch outside.", "B": "He’s working at his desk.", "C": "He’s making a phone call.", "D": "He’s sitting on the grass."}', 'B', NULL, 2),
(101, 'LISTENING','She’s preparing dinner.', '{"A": "She’s washing her clothes.", "B": "She’s doing the dishes.", "C": "She’s cleaning her bedroom.", "D": "She’s preparing dinner."}', 'D', NULL, 3),
(101, 'LISTENING','A woman is distributing handouts.', '{"A": "A woman is giving out presents.", "B": "A woman is leading a workshop.", "C": "A woman is distributing handouts.", "D": "A woman is registering for a seminar."}', 'C', NULL, 4),
(101, 'LISTENING','The lake is being used for recreation.', '{"A": "The waves are crashing against the rocks.", "B": "The park is surrounded by water.", "C": "There’s a fountain in the water.", "D": "The lake is being used for recreation."}', 'D', NULL, 5),
(101, 'LISTENING','The woman is being examined.', '{"A": "The woman is making an appointment.", "B": "The woman is being examined.", "C": "The doctor is looking at the chart.", "D": "The doctor is being paged."}', 'B', NULL, 6),
(101, 'LISTENING','There are houses on both sides of the river.', '{"A": "There is a ferry on the canal.", "B": "People are diving into the water.", "C": "Most of the houses are being restored.", "D": "There are houses on both sides of the river."}', 'D', NULL, 7),
(101, 'LISTENING','He’s buying a train ticket.', '{"A": "He’s wearing a business suit.", "B": "He’s getting on the train.", "C": "He’s unloading the bags.", "D": "He’s buying a train ticket."}', 'D', NULL, 8),
(101, 'LISTENING','They’re putting on a performance.', '{"A": "They’re putting on a performance.", "B": "They’re singing in a choir.", "C": "They’re unpacking their instruments.", "D": "They’re going to a concert."}', 'A', NULL, 9),
(101, 'LISTENING','The waiter is carrying plates of food.', '{"A": "The waiter is carrying plates of food.", "B": "The cafeteria has been closed down.", "C": "The food is displayed in glass cabinets.", "D": "The cafe is inside a shopping mall."}', 'A', NULL, 10);

-- Insert data for PART 2 TOEIC no3
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(151, 'LISTENING','She’s coming down the stairs.', '{"A": "She’s coming down the stairs.", "B": "She''s riding the escalator.", "C": "She’s taking the elevator.", "D": "She’s going up the ladder."}', 'A', NULL, 1),
(151, 'LISTENING','They’re doing the dishes.', '{"A": "They’re doing the dishes.", "B": "They’re moving the furniture.", "C": "They’re unpacking some boxes.", "D": "They’re installing some equipment."}', 'A', NULL, 2),
(151, 'LISTENING','A man is registering for a conference.', '{"A": "A man is registering for a conference.", "B": "A man is signing some books.", "C": "A man is browsing around the library.", "D": "A man is reading a pamphlet."}', 'A', NULL, 3),
(151, 'LISTENING','There is a tree behind the bench.', '{"A": "There is a tree behind the bench.", "B": "The sidewalk is being repaved.", "C": "The hedge is being trimmed.", "D": "The bench is positioned next to a house."}', 'A', NULL, 4),
(151, 'LISTENING','People are buying train tickets.', '{"A": "People are buying train tickets.", "B": "People are using public transportation.", "C": "People are waiting at a bus terminal.", "D": "People are looking at a subway map."}', 'A', NULL, 5),
(151, 'LISTENING','The café is closed for business.', '{"A": "The café is closed for business.", "B": "Some of the trees are losing their leaves.", "C": "All of the parasols are being put away.", "D": "The tables are arranged around the courtyard."}', 'A', NULL, 6),
(151, 'LISTENING','The woman has checked out of the hotel.', '{"A": "The woman has checked out of the hotel.", "B": "The woman is ordering room service.", "C": "The woman has left her bag on the ground.", "D": "The woman is weighing her luggage."}', 'A', NULL, 7),
(151, 'LISTENING','The waste containers are labeled.', '{"A": "The waste containers are labeled.", "B": "The garbage is being collected.", "C": "The trash cans are being emptied.", "D": "The litter is lying on the floor."}', 'A', NULL, 8),
(151, 'LISTENING','The tables have been stacked up.', '{"A": "The tables have been stacked up.", "B": "The leftovers have been cleared away.", "C": "The restaurant is full of customers.", "D": "The dining hall has been set up."}', 'A', NULL, 9),
(151, 'LISTENING','They’re working in the mall.', '{"A": "They’re working in the mall.", "B": "They’re holding hands.", "C": "They’re putting on their backpacks.", "D": "They’re hiking through the woods."}', 'A', NULL, 10);

-- Insert data for PART 2 TOEIC no4
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(201, 'LISTENING','He’s changing the tires.', '{"A": "He’s changing the tires.", "B": "He’s washing the vehicle.", "C": "He’s checking the engine.", "D": "He’s pushing the car."}', 'A', NULL, 1),
(201, 'LISTENING','The taxis are stuck in traffic.', '{"A": "The taxis are stuck in traffic.", "B": "The taxis are lined up in a row.", "C": "The taxis have stopped at an intersection.", "D": "The taxis are being serviced."}', 'A', NULL, 2),
(201, 'LISTENING','The workers are installing the computer.', '{"A": "The workers are installing the computer.", "B": "One woman is drinking from a glass.", "C": "The workers are attending a presentation.", "D": "One woman is pointing at the screen."}', 'A', NULL, 3),
(201, 'LISTENING','They’re looking at a photograph.', '{"A": "They’re looking at a photograph.", "B": "They’re walking along the path.", "C": "They’re having their picture taken.", "D": "They’re buying a camera."}', 'A', NULL, 4),
(201, 'LISTENING','The yachts are facing in the same direction.', '{"A": "The yachts are facing in the same direction.", "B": "There are several boats in the harbor.", "C": "There are many ships tied up together.", "D": "The wharf is being constructed."}', 'A', NULL, 5),
(201, 'LISTENING','There is a bus terminal across the street.', '{"A": "There is a bus terminal across the street.", "B": "The pedestrians are using the underpass.", "C": "Some of the buildings are being renovated.", "D": "Most of the people are wearing coats."}', 'A', NULL, 6),
(201, 'LISTENING','The library is full of visitors.', '{"A": "The library is full of visitors.", "B": "The shelves are being restocked.", "C": "The books have been left lying around.", "D": "The reading materials have been assembled."}', 'A', NULL, 7),
(201, 'LISTENING','The people are leaning against the wall.', '{"A": "The people are leaning against the wall.", "B": "The woman is posting a notice on the wall.", "C": "The people are talking beside a bulletin board.", "D": "The woman is indicating something on a chart."}', 'A', NULL, 8),
(201, 'LISTENING','They’re preparing breakfast.', '{"A": "They’re preparing breakfast.", "B": "They’re eating out together.", "C": "They’re reading the menu.", "D": "They’re pointing at the waiter."}', 'A', NULL, 9),
(201, 'LISTENING','He’s repairing his bicycle.', '{"A": "He’s repairing his bicycle.", "B": "He’s riding a motorcycle.", "C": "He’s holding the handlebars.", "D": "He’s adjusting the bike seat."}', 'A', NULL, 10);

-- Insert data for PART 2 TOEIC no5
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(251, 'LISTENING','They’re holding tickets for the train.', '{"A": "They’re holding tickets for the train.", "B": "They’re walking through the train.", "C": "They’re doing some window-shopping.", "D": "They’re strolling along the platform."}', 'A', NULL, 1),
(251, 'LISTENING','A man is swimming in the ocean.', '{"A": "A man is swimming in the ocean.", "B": "A man is facing his child.", "C": "A man is sharing some fish.", "D": "A man is standing on the beach."}', 'A', NULL, 2),
(251, 'LISTENING','The buses have been parked at the terminal.', '{"A": "The buses have been parked at the terminal.", "B": "The buses are filled with passengers.", "C": "The buses have left the station.", "D": "The buses are being washed off."}', 'A', NULL, 3),
(251, 'LISTENING','He’s holding onto the handrail.', '{"A": "He’s holding onto the handrail.", "B": "He’s focusing on his laptop.", "C": "He’s setting down his backpack.", "D": "He’s coming down the stairs."}', 'A', NULL, 4),
(251, 'LISTENING','Renovations are underway in the town.', '{"A": "Renovations are underway in the town.", "B": "The houses have been built close to the river.", "C": "Three roadways run under the bridge.", "D": "Buildings stand on both sides of the water."}', 'A', NULL, 5),
(251, 'LISTENING','The man is helping her exercise.', '{"A": "The man is helping her exercise.", "B": "The woman is walking out of the room.", "C": "The woman is weighing herself.", "D": "The man is lifting a dumbbell."}', 'A', NULL, 6),
(251, 'LISTENING','The restaurant is crowded with diners.', '{"A": "The restaurant is crowded with diners.", "B": "Food has been served at a party.", "C": "The customer is setting the table.", "D": "Two people are eating outdoors."}', 'A', NULL, 7),
(251, 'LISTENING','There are many types of fruit on display.', '{"A": "There are many types of fruit on display.", "B": "There are signs hanging from the ceiling.", "C": "There are fruit bins near the register.", "D": "There are pieces of fruit being eaten."}', 'A', NULL, 8),
(251, 'LISTENING','Construction equipment has been loaded onto a truck.', '{"A": "Construction equipment has been loaded onto a truck.", "B": "The farmers are digging in the field.", "C": "One machine is dumping dirt into the other.", "D": "The highway has been closed for maintenance work."}', 'A', NULL, 9),
(251, 'LISTENING','They are seeing a patient.', '{"A": "They are seeing a patient.", "B": "They are wearing masks.", "C": "They are behind a counter.", "D": "They are in a laboratory."}', 'A', NULL, 10);

-- Insert data for PART 2 TOEIC no1
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(301, 'READING','Where did you put the file?', '{"A": "Sometime last week.", "B": "No, he hasn’t filed it yet.", "C": "In the office cabinet."}', 'C', '', 11),
(301, 'READING','Could you give me a copy of the report?', '{"A": "No, thanks. I don’t need one.", "B": "Sure, here you are.", "C": "The photocopier is on the 2nd floor."}', 'B', '', 12),
(301, 'READING','What is the soup of the day?', '{"A": "It’s tomorrow.", "B": "Clam chowder.", "C": "No, I’ll get something else."}', 'B', '', 13),
(301, 'READING','How long is the flight from Santiago?', '{"A": "To New York.", "B": "10 hours.", "C": "No, not really."}', 'B', '', 14),
(301, 'READING','Did anyone call for me while I was away?', '{"A": "How long will you be gone?", "B": "Well, it has been a while.", "C": "Nothing important."}', 'C', '', 15),
(301, 'READING','Could you give me a wake-up call at 7 A.M.?', '{"A": "I’ve already woken up.", "B": "No, he didn’t call.", "C": "No problem, sir."}', 'C', '', 16),
(301, 'READING','I see you bought a new cell phone.', '{"A": "Yes, I lost my old one.", "B": "A little under $200.", "C": "Where did you buy it?"}', 'A', '', 17),
(301, 'READING','What kind of skirt are you looking for?', '{"A": "Yes, it was very kind of her.", "B": "Preferably something in silk.", "C": "It looks all right."}', 'B', '', 18),
(301, 'READING','Isn’t Mr. Knight retiring at the end of the year?', '{"A": "Yes, I’m very tired as well.", "B": "Not that I know of.", "C": "Yes, he did."}', 'B', '', 19),
(301, 'READING','The work schedule has been revised, right?', '{"A": "He’s my advisor.", "B": "Yes, I’ll send it to you now.", "C": "By next weekend at the latest."}', 'C', '', 20),
(301, 'READING','Where did you end up going on vacation? Miami or Las Vegas?', '{"A": "I finally decided on Miami.", "B": "Yes, they’re both interesting destinations.", "C": "I know! Our vacation is nearly over."}', 'A', '', 21),
(301, 'READING','Would you mind if I changed the channel?', '{"A": "I didn’t change it.", "B": "Sure, go ahead.", "C": "No, the tunnel isn’t that long."}', 'B', '', 22),
(301, 'READING','Why is the senator arranging a press conference?', '{"A": "On a wide range of products.", "B": "It was very impressive.", "C": "To discuss the new legislation."}', 'C', '', 23),
(301, 'READING','Can I have a look at your concert program?', '{"A": "I’m afraid I didn’t get one either.", "B": "I’m very concerned about it, too.", "C": "It’s a computer program."}', 'A', '', 24),
(301, 'READING','When should we gather at the tour bus?', '{"A": "At 12:30 sharp.", "B": "The gathering was last month.", "C": "At the main entrance."}', 'A', '', 25),
(301, 'READING','How did Mr. Johnson react to the news?', '{"A": "I never watch the news.", "B": "He was very relieved.", "C": "He is an actor."}', 'B', '', 26),
(301, 'READING','Ms. Watson is flying in from New Jersey for a meeting.', '{"A": "Isn’t that the old version?", "B": "No, she wasn’t on my flight either.", "C": "You’d better collect her from the airport."}', 'C', '', 27),
(301, 'READING','Who gave you permission to park there?', '{"A": "The assistant in the booth.", "B": "Admission is $2.", "C": "Don’t worry. I gave it back."}', 'A', '', 28),
(301, 'READING','What did you do with the handouts?', '{"A": "I distributed them to the participants.", "B": "No, it’s inside.", "C": "Sorry, I can’t help you at the moment."}', 'A', '', 29),
(301, 'READING','Where is the team lunch being held?', '{"A": "I think it’s Friday next week.", "B": "At the Indian restaurant across the road.", "C": "Yes, the launch was very successful."}', 'B', '', 30),
(301, 'READING','Will all employees receive a bonus this year, or just a few?', '{"A": "Only the top performers will be rewarded.", "B": "Yes, that’s what I heard as well.", "C": "I worked extra hours."}', 'A', '', 31),
(301, 'READING','Which seminar are you going to attend?', '{"A": "The one on asset management.", "B": "I didn’t go there.", "C": "Because he tends to change his mind."}', 'A', '', 32),
(301, 'READING','Human Resources haven’t found a replacement for Mr. Allen, have they?', '{"A": "No, but there are some promising candidates.", "B": "It was founded several years ago.", "C": "My place isn’t far from here."}', 'A', '', 33),
(301, 'READING','Haven’t you been to the new shopping mall yet?', '{"A": "Yes, it has been.", "B": "Small size, please.", "C": "I’m planning to go there next weekend."}', 'C', '', 34),
(301, 'READING','We’re thinking about renovating our kitchen and bathroom.', '{"A": "No, I think we should put it in the living room.", "B": "Relocating can be very expensive.", "C": "I can introduce a great builder."}', 'C', '', 35),
(301, 'READING','Is your office on 1st floor or the 2nd?', '{"A": "Actually it’s on the 5th floor", "B": "In the large office complex downtown", "C": "Thank you for visiting."}', 'A', '', 36),
(301, 'READING','Have you seen Andrew around the office lately?', '{"A": "I saw him just this morning.", "B": "Were you late again this morning?", "C": "In the official guidelines."}', 'A', '', 37),
(301, 'READING','You’re staying at the Pembridge Hotel, aren’t you?', '{"A": "I thought it was very comfortable.", "B": "I’m not going yet.", "C": "Yes, it’s quite close to the station."}', 'C', '', 38),
(301, 'READING','Who is going to make the opening speech at the conference?', '{"A": "At the Hyatt Hotel.", "B": "A partner from Worrell and Jones.", "C": "Before the event starts on the first day."}', 'B', '', 39),
(301, 'READING','Why did the marketing team fail to meet the project deadline?', '{"A": "Because the test was extremely difficult.", "B": "On or before the 15th of July.", "C": "Do you think they might be understaffed?"}', 'C', '', 40);

-- Insert data for PART 2 TOEIC no2
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(351, 'READING','Where can I find the marketing report?', '{"A": "It’s on the server.", "B": "I already sent it to you.", "C": "It’s in my office."}', 'A', '', 11),
(351, 'READING','Can you recommend a good restaurant?', '{"A": "The one across the street is great.", "B": "I don’t like eating out.", "C": "I think the office cafeteria is good."}', 'A', '', 12),
(351, 'READING','What time does the conference call start?', '{"A": "It starts at 10:00 AM.", "B": "I’m not sure.", "C": "I need to check."}', 'A', '', 13),
(351, 'READING','How should I send the payment?', '{"A": "You can wire it.", "B": "You can mail it.", "C": "You should pay online."}', 'A', '', 14),
(351, 'READING','Where is the nearest restroom?', '{"A": "It’s down the hall to the left.", "B": "I don’t know.", "C": "It’s in the building next door."}', 'A', '', 15),
(351, 'READING','Have you finished the project?', '{"A": "Yes, it’s done.", "B": "Not yet, I’m still working on it.", "C": "I haven’t started yet."}', 'A', '', 16),
(351, 'READING','Why are you late?', '{"A": "I missed the bus.", "B": "I didn’t feel well.", "C": "I had a meeting."}', 'A', '', 17),
(351, 'READING','Where did you get that information?', '{"A": "From the email I received.", "B": "From the internet.", "C": "From a colleague."}', 'A', '', 18),
(351, 'READING','Are you available for a meeting tomorrow?', '{"A": "Yes, I’m free.", "B": "No, I have another appointment.", "C": "I need to check my calendar."}', 'A', '', 19),
(351, 'READING','How do I reach the customer service department?', '{"A": "You can call the hotline.", "B": "Just visit their website.", "C": "You can send an email."}', 'A', '', 20),
(351, 'READING','What time does the store close?', '{"A": "At 6:00 PM.", "B": "At 8:00 PM.", "C": "At 10:00 PM."}', 'A', '', 21),
(351, 'READING','Where did you put my laptop?', '{"A": "It’s on your desk.", "B": "I didn’t touch it.", "C": "I put it in the drawer."}', 'A', '', 22),
(351, 'READING','Are you familiar with the new software?', '{"A": "Yes, I’ve used it before.", "B": "No, I haven’t used it yet.", "C": "I heard about it."}', 'A', '', 23),
(351, 'READING','Could you explain this report to me?', '{"A": "I can go over it with you.", "B": "It’s too complicated.", "C": "I can’t explain that."}', 'A', '', 24),
(351, 'READING','Where is the nearest post office?', '{"A": "It’s down the street.", "B": "I don’t know.", "C": "There’s one on the next block."}', 'A', '', 25),
(351, 'READING','What are your working hours?', '{"A": "From 9 AM to 5 PM.", "B": "From 8 AM to 4 PM.", "C": "We work flexibly."}', 'A', '', 26),
(351, 'READING','Have you completed the task yet?', '{"A": "Yes, I finished it this morning.", "B": "I’m still working on it.", "C": "I haven’t started yet."}', 'A', '', 27),
(351, 'READING','When is the deadline for the report?', '{"A": "It’s due by Friday.", "B": "The deadline has passed.", "C": "It’s next month."}', 'A', '', 28),
(351, 'READING','Do you need assistance with the presentation?', '{"A": "Yes, I need help.", "B": "No, I can handle it.", "C": "I need some information."}', 'A', '', 29),
(351, 'READING','How do I reset my password?', '{"A": "You can reset it online.", "B": "You need to call IT support.", "C": "I can reset it for you."}', 'A', '', 30);

-- Insert data for PART 2 TOEIC no3
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(401, 'READING','Do you need help with your luggage?', '{"A": "No, I’m fine.", "B": "Yes, please.", "C": "I can carry it myself."}', 'B', '', 11),
(401, 'READING','What time does the meeting start?', '{"A": "At 9:00 AM.", "B": "At 10:00 AM.", "C": "At noon."}', 'A', '', 12),
(401, 'READING','Have you confirmed your attendance for the event?', '{"A": "Yes, I’ve confirmed it.", "B": "No, I still need to confirm.", "C": "I won’t be able to attend."}', 'A', '', 13),
(401, 'READING','Where do I find the presentation slides?', '{"A": "They’re in the shared folder.", "B": "I don’t know.", "C": "I haven’t uploaded them yet."}', 'A', '', 14),
(401, 'READING','Did you send the invitation email?', '{"A": "Yes, I’ve already sent it.", "B": "No, I forgot.", "C": "I’m planning to send it soon."}', 'A', '', 15),
(401, 'READING','Can you provide an update on the project?', '{"A": "Yes, everything is on track.", "B": "No, there have been some delays.", "C": "I don’t have an update."}', 'A', '', 16),
(401, 'READING','What should I bring to the conference?', '{"A": "Your business cards.", "B": "Your laptop.", "C": "Just a notebook."}', 'A', '', 17),
(401, 'READING','How was the flight?', '{"A": "It was smooth.", "B": "It was delayed.", "C": "I missed the flight."}', 'A', '', 18),
(401, 'READING','Where can I find the team members?', '{"A": "They are in the conference room.", "B": "They are in the cafeteria.", "C": "They are in the parking lot."}', 'A', '', 19),
(401, 'READING','Would you like to join us for lunch?', '{"A": "Sure, I’d love to.", "B": "No, I’m busy.", "C": "Maybe later."}', 'A', '', 20),
(401, 'READING','How long will the meeting last?', '{"A": "About an hour.", "B": "A couple of hours.", "C": "It could go all day."}', 'A', '', 21),
(401, 'READING','When is the deadline for the report?', '{"A": "By the end of the week.", "B": "Next month.", "C": "Next Monday."}', 'A', '', 22),
(401, 'READING','Where is the nearest pharmacy?', '{"A": "It’s around the corner.", "B": "It’s on the main street.", "C": "I’m not sure."}', 'A', '', 23),
(401, 'READING','Do you have a moment to discuss the project?', '{"A": "Yes, I’m free.", "B": "I’m in a meeting.", "C": "I’m busy right now."}', 'A', '', 24),
(401, 'READING','Can you send me the report by email?', '{"A": "Yes, I’ll send it now.", "B": "I’ll send it later.", "C": "I’ll send it tomorrow."}', 'A', '', 25),
(401, 'READING','Are we going to the conference together?', '{"A": "Yes, we’re meeting at 8 AM.", "B": "No, I’m going separately.", "C": "I haven’t decided yet."}', 'A', '', 26),
(401, 'READING','Who is responsible for the marketing campaign?', '{"A": "John is in charge.", "B": "Sarah is handling it.", "C": "We all are."}', 'A', '', 27),
(401, 'READING','What time is your flight tomorrow?', '{"A": "It’s at 7:30 AM.", "B": "It’s at 9:00 AM.", "C": "It’s at noon."}', 'A', '', 28),
(401, 'READING','Where is the meeting room?', '{"A": "It’s on the 5th floor.", "B": "It’s in the basement.", "C": "It’s next to the cafeteria."}', 'A', '', 29),
(401, 'READING','How long will the project take?', '{"A": "About 3 months.", "B": "It will take a few weeks.", "C": "It will take a year."}', 'A', '', 30);

-- Insert data for PART 3 TOEIC no1
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(451, 'READING','Where do the speakers work?', '{"A": "At a hotel.", "B": "At an art gallery.", "C": "At a hardware store.", "D": "At a travel agency."}', 'A', '', 32),
(451, 'READING','Why was a building temporarily closed?', '{"A": "To take inventory.", "B": "To host an event.", "C": "To complete a renovation.", "D": "To celebrate a holiday."}', 'C', '', 33),
(451, 'READING','What is the man going to do next?', '{"A": "Post some flyers.", "B": "Send customers an e-mail.", "C": "Place a food order.", "D": "Contact the maintenance department."}', 'B', '', 34),
(451, 'READING','What are the speakers planning?', '{"A": "A company dinner.", "B": "A conference schedule.", "C": "An upcoming trip.", "D": "A factory inspection."}', 'A', '', 35),
(451, 'READING','What does the woman suggest?', '{"A": "Inviting a guest speaker.", "B": "Reserving a different venue.", "C": "Checking a budget.", "D": "Postponing a party."}', 'B', '', 36),
(451, 'READING','What does the woman say will be provided?', '{"A": "Name tags.", "B": "A city tour.", "C": "Transportation.", "D": "Entertainment."}', 'C', '', 37),
(451, 'READING','What are the speakers mainly discussing?', '{"A": "A store sign.", "B": "A Web site.", "C": "Some uniforms.", "D": "Some business cards."}', 'D', '', 38),
(451, 'READING','What suggestion does the man make?', '{"A": "Adding display racks.", "B": "Giving a demonstration.", "C": "Researching some suppliers.", "D": "Advertising a business’ hours."}', 'C', '', 39),
(451, 'READING','What does Ana offer to do?', '{"A": "Lead a training session.", "B": "Greet a client.", "C": "Update a list.", "D": "Revise an announcement."}', 'A', '', 40),
(451, 'READING','What type of business is the man calling?', '{"A": "A bookstore.", "B": "A restaurant.", "C": "A clothing shop.", "D": "A printing shop."}', 'D', '', 41),
(451, 'READING','What will happen next week?', '{"A": "A class will begin.", "B": "A shipment will arrive.", "C": "A location will change.", "D": "A sale will end."}', 'B', '', 42),
(451, 'READING','What information does the woman ask for?', '{"A": "A bank account number.", "B": "A mailing address.", "C": "A discount code.", "D": "A telephone number."}', 'D', '', 43),
(451, 'READING','What is the woman concerned about?', '{"A": "The quality of some fabric.", "B": "The price of a shipment.", "C": "The size of some furniture.", "D": "The noise from some construction."}', 'C', '', 44),
(451, 'READING','What does the man say his team will do at the woman’s house?', '{"A": "Paint a living room.", "B": "Assemble a product.", "C": "Take some measurements.", "D": "Remove some machinery."}', 'B', '', 45),
(451, 'READING','What does the woman ask the man to do?', '{"A": "Resubmit an order form.", "B": "Send some samples.", "C": "Go to a different address.", "D": "Change a delivery date."}', 'D', '', 46),
(451, 'READING','Why does the man want to hire a temporary employee?', '{"A": "To hand out brochures.", "B": "To design a Web site.", "C": "To sort through some documents.", "D": "To pick up some office equipment."}', 'C', '', 47),
(451, 'READING','According to the man, what does the job require?', '{"A": "Sales experience.", "B": "Public speaking skills.", "C": "Interior decorating experience.", "D": "Computer skills."}', 'A', '', 48),
(451, 'READING','What does the man ask the woman to do?', '{"A": "Check a budget.", "B": "Sign a contract.", "C": "Brainstorm marketing ideas.", "D": "Prepare some invoices."}', 'B', '', 49),
(451, 'READING','Where do the speakers most likely work?', '{"A": "At a hotel.", "B": "At a restaurant.", "C": "At a convention hall.", "D": "At an auto repair shop."}', 'C', '', 50),
(451, 'READING','What does the woman say about her car?', '{"A": "She will loan it to a friend.", "B": "She does not use it often.", "C": "It was recently purchased.", "D": "It needs to be fixed."}', 'D', '', 51),
(451, 'READING','What does the woman mean when she says, "Thursday is my mother’s birthday?"', '{"A": "She is inviting the man to a party.", "B": "She cannot work on Thursday night.", "C": "She has to buy a gift before Thursday.", "D": "She forgot to update a calendar."}', 'B', '', 52),
(451, 'READING','What most likely is the man’s position?', '{"A": "A maintenance worker.", "B": "A government official.", "C": "An editor.", "D": "An accountant."}', 'A', '', 53),
(451, 'READING','What do the women do at their company?', '{"A": "They arrange travel.", "B": "They provide legal assistance.", "C": "They organize training sessions.", "D": "They manage company inventory."}', 'C', '', 54),
(451, 'READING','What does the man ask about?', '{"A": "Free parking.", "B": "Technical support.", "C": "Payment options.", "D": "Printing supplies."}', 'C', '', 55),
(451, 'READING','Which industry do the speakers most likely work in?', '{"A": "Health care.", "B": "Architecture.", "C": "Tourism.", "D": "Fashion."}', 'C', '', 56),
(451, 'READING','What does the woman mean when she says, "My meeting was canceled"?', '{"A": "She cannot answer a question.", "B": "She is available to discuss an issue.", "C": "She is confused by a schedule change.", "D": "She is worried a project will be delayed."}', 'B', '', 57),
(451, 'READING','What will the woman most likely do next?', '{"A": "Call a vendor.", "B": "Distribute a questionnaire.", "C": "Review some designs.", "D": "Contact some colleagues."}', 'C', '', 58),
(451, 'READING','What is the topic of an upcoming seminar?', '{"A": "Payroll procedures.", "B": "Videoconferencing tools.", "C": "Computer upgrades.", "D": "Password security."}', 'D', '', 59),
(451, 'READING','What aspect of the seminar do the speakers disagree about?', '{"A": "How long it should last.", "B": "How it should be announced.", "C": "Whether attendance should be required.", "D": "Whether refreshments should be served."}', 'C', '', 60),
(451, 'READING','What does the woman want to distribute after the seminar?', '{"A": "A survey.", "B": "A manual.", "C": "Some paychecks.", "D": "Some hardware."}', 'A', '', 61),
(451, 'READING','Who most likely is the man?', '{"A": "A fitness coach.", "B": "A teacher.", "C": "A medical doctor.", "D": "A receptionist."}', 'B', '', 62),
(451, 'READING','What does the woman ask the man about?', '{"A": "Requirements for a job.", "B": "Alternative types of exercise.", "C": "Available appointment times.", "D": "Operating hours of a business."}', 'C', '', 63),
(451, 'READING','Look at the graphic. When will the woman probably go to the community center in the spring?', '{"A": "On Tuesdays.", "B": "On Wednesdays.", "C": "On Thursdays.", "D": "On Fridays."}', 'B', '', 64),
(451, 'READING','What does the man say he is doing tonight?', '{"A": "Taking a flight.", "B": "Eating in a restaurant.", "C": "Seeing a performance.", "D": "Visiting a friend."}', 'C', '', 65),
(451, 'READING','Look at the graphic. Which train line will the man most likely take?', '{"A": "The North Line.", "B": "The East Line.", "C": "The South Line.", "D": "The West Line."}', 'A', '', 66),
(451, 'READING','What does the man ask about a bus?', '{"A": "Whether he needs a different ticket.", "B": "Whether there are reserved seats.", "C": "How long the ride will take.", "D": "How often the bus runs."}', 'C', '', 67),
(451, 'READING','Why is the woman at the store?', '{"A": "To arrange a delivery.", "B": "To exchange a purchase.", "C": "To request an instruction manual.", "D": "To complain about an incorrect charge."}', 'B', '', 68),
(451, 'READING','What is the woman’s job?', '{"A": "Jazz musician.", "B": "Studio photographer.", "C": "Carpenter.", "D": "Electrical engineer."}', 'C', '', 69),
(451, 'READING','Look at the graphic. What model does the man recommend?', '{"A": "F-12.", "B": "A-66.", "C": "N-48.", "D": "C-94."}', 'D', '', 70);

-- Insert data for PART 3 TOEIC no2
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(501, 'READING','Where are the speakers?', '{"A": "At an airport", "B": "At a restaurant", "C": "At a theater", "D": "At a hotel"}', 'A', '', 1),
(501, 'READING','What does the woman ask the man for?', '{"A": "His reservation number", "B": "His name", "C": "His departure day", "D": "His credit card"}', 'A', '', 2),
(501, 'READING','What will the man most likely do next?', '{"A": "Park his car", "B": "Upgrade a reservation", "C": "Buy a snack", "D": "Go to the pool"}', 'A', '', 3),
(501, 'READING','Who most likely is the man?', '{"A": "A painter", "B": "A security guard", "C": "A bank teller", "D": "A property manager"}', 'D', '', 4),
(501, 'READING','What problem does the woman have?', '{"A": "She found a mistake on a bill.", "B": "She cannot locate a door key.", "C": "An air conditioner is not working.", "D": "An apartment is too noisy."}', 'C', '', 5),
(501, 'READING','What information does the man ask for?', '{"A": "An address", "B": "A security code", "C": "A telephone number", "D": "An appointment time"}', 'B', '', 6),
(501, 'READING','Where do the speakers most likely work?', '{"A": "At a manufacturing plant", "B": "At a delivery company", "C": "At a fitness center", "D": "At a grocery store"}', 'B', '', 7),
(501, 'READING','According to the woman, what does a decision depend on?', '{"A": "Employee availability", "B": "Government regulations", "C": "A price", "D": "A timeline"}', 'D', '', 8),
(501, 'READING','What does the man say he will do?', '{"A": "Check delivery dates", "B": "Schedule an inspection", "C": "Contact a supplier", "D": "Test a product"}', 'A', '', 9),
(501, 'READING','What is the man’s job?', '{"A": "University professor", "B": "Newspaper reporter", "C": "Flight attendant", "D": "Tour guide"}', 'D', '', 10),
(501, 'READING','What does the man say he likes about the job?', '{"A": "Meeting city officials", "B": "Traveling to other countries", "C": "Learning about local history", "D": "Attending special celebrations"}', 'B', '', 11),
(501, 'READING','What does the woman ask the man to do?', '{"A": "Write an article", "B": "Work more hours", "C": "Train new employees", "D": "Organize an event"}', 'A', '', 12),
(501, 'READING','What will be the topic of the woman’s article?', '{"A": "Music festivals", "B": "Local restaurants", "C": "Farmers markets", "D": "Sporting events"}', 'C', '', 13),
(501, 'READING','What does the man ask the woman about?', '{"A": "Interviewing some vendors", "B": "Reformatting some images", "C": "Extending a deadline", "D": "Making travel arrangements"}', 'A', '', 14),
(501, 'READING','What does the man mean when he says, "I don’t think Elena has any assignments"?', '{"A": "A colleague completes tasks quickly.", "B": "A colleague may be available for a job.", "C": "An office does not need more staff.", "D": "A schedule may be incorrect."}', 'B', '', 15),
(501, 'READING','Why does the man congratulate the woman?', '{"A": "She recently published a book.", "B": "She just received a promotion.", "C": "She acquired a major account.", "D": "She completed a business course."}', 'B', '', 16),
(501, 'READING','What does the man ask the woman to do?', '{"A": "Update a reservation", "B": "Meet with a new client", "C": "Submit a budget report", "D": "Give a talk to staff members"}', 'D', '', 17),
(501, 'READING','Where does the woman say she will be going?', '{"A": "To a fund-raising event", "B": "To a convention", "C": "On a vacation", "D": "On a promotional tour"}', 'B', '', 18),
(501, 'READING','Who most likely are the men?', '{"A": "Real estate agents", "B": "Interior designers", "C": "Marketing executives", "D": "Bank managers"}', 'B', '', 19),
(501, 'READING','What does the woman want to discuss first?', '{"A": "A delivery time", "B": "A rental fee", "C": "Some flooring options", "D": "Some machinery upgrades"}', 'C', '', 20),
(501, 'READING','What will the woman most likely do next?', '{"A": "Look at a catalog", "B": "Cancel a meeting", "C": "Review a receipt", "D": "Call a supervisor"}', 'A', '', 21),
(501, 'READING','What is the woman planning to do at two o’clock?', '{"A": "Go to the airport", "B": "Receive a shipment", "C": "Meet with a customer", "D": "Give a workshop"}', 'B', '', 22),
(501, 'READING','What problem is the woman having?', '{"A": "Her log-in information has expired.", "B": "Her laptop cable does not work.", "C": "Her reservation was not confirmed.", "D": "Her mobile phone is missing."}', 'C', '', 23),
(501, 'READING','What does the man tell the woman to do?', '{"A": "Search in her office", "B": "Visit an electronics store", "C": "Borrow some equipment", "D": "Contact a service team member"}', 'D', '', 24),
(501, 'READING','Where is the conversation taking place?', '{"A": "At a park", "B": "At a café", "C": "At a furniture store", "D": "At a supermarket"}', 'B', '', 25),
(501, 'READING','What does Luisa suggest that the man do?', '{"A": "Open a window", "B": "Use a coupon", "C": "Visit a plant shop", "D": "Extend business hours"}', 'B', '', 26),
(501, 'READING','What does the man ask Luisa for?', '{"A": "A list of prices", "B": "A deadline extension", "C": "Some coffee", "D": "Some photographs"}', 'A', '', 27),
(501, 'READING','What problem does the woman mention?', '{"A": "A product is not selling well.", "B": "A position is vacant.", "C": "A proposal was not accepted.", "D": "A supervisor is busy."}', 'A', '', 28),
(501, 'READING','Why does the woman say, "He’s never done that before"?', '{"A": "To express concern", "B": "To request more help", "C": "To approve a decision", "D": "To offer some praise"}', 'A', '', 29),
(501, 'READING','What does the man say he will do?', '{"A": "Write a report", "B": "Conduct an interview", "C": "Schedule a meeting", "D": "Post an advertisement"}', 'C', '', 30),
(501, 'READING','Why does the man want to return an item?', '{"A": "It has a stain.", "B": "It has a tear.", "C": "It is the wrong color.", "D": "It is too large."}', 'D', '', 31),
(501, 'READING','Look at the graphic. Which item does the man want to return?', '{"A": "The jacket", "B": "The sweater", "C": "The scarf", "D": "The T-shirt"}', 'A', '', 32),
(501, 'READING','What does the woman offer to do for the man?', '{"A": "Issue a refund to his credit card", "B": "Set up an account for him", "C": "Consult with a manager", "D": "Call another branch store"}', 'A', '', 33),
(501, 'READING','Who most likely is the woman?', '{"A": "A postal worker", "B": "A delivery driver", "C": "A repair technician", "D": "A building supervisor"}', 'D', '', 34),
(501, 'READING','What problem does the woman mention?', '{"A": "A package has been damaged.", "B": "A vehicle is not working.", "C": "Some residents are not home.", "D": "Some information is missing."}', 'A', '', 35),
(501, 'READING','Look at the graphic. Where will the woman go next?', '{"A": "To Building 1", "B": "To Building 2", "C": "To Building 3", "D": "To Building 4"}', 'B', '', 36),
(501, 'READING','Look at the graphic. What is the status of the woman’s flight?', '{"A": "40 minutes late", "B": "On time", "C": "55 minutes late", "D": "25 minutes late"}', 'B', '', 37),
(501, 'READING','What kind of company do the speakers work for?', '{"A": "A fabric manufacturer", "B": "A clothing store", "C": "A travel agency", "D": "A newspaper publisher"}', 'C', '', 38),
(501, 'READING','What does the man say he is going to do?', '{"A": "Open another bank account", "B": "Extend business hours", "C": "Review a contract", "D": "Change a meeting time"}', 'C', '', 39);

-- Insert data for PART 3 TOEIC no3
INSERT INTO public.question (part_id, grading_type, content, options, correct_answer, explanation, order_number) VALUES
(551, 'READING','Where does the woman say she wants to go?', '{"A": "To an airport", "B": "To a beach", "C": "To a hotel", "D": "To a fitness center"}', 'A', '', 1),
(551, 'READING','Who most likely is the man?', '{"A": "An auto mechanic", "B": "A local musician", "C": "A security guard", "D": "A bus driver"}', 'C', '', 2),
(551, 'READING','Why will the woman return home late?', '{"A": "She is working overtime.", "B": "She has a flight delay.", "C": "She is attending a concert.", "D": "She is eating at a restaurant"}', 'B', '', 3),
(551, 'READING','Where do the speakers most likely work?', '{"A": "At an appliance manufacturer", "B": "At a construction firm", "C": "At a grocery store", "D": "At an apartment complex"}', 'D', '', 4),
(551, 'READING','What does the woman say she will review?', '{"A": "A budget", "B": "A contract", "C": "A job posting", "D": "An instruction manual"}', 'B', '', 5),
(551, 'READING','What does the man hope to do this afternoon?', '{"A": "Schedule an interview", "B": "Arrange a discount", "C": "Make a delivery", "D": "Print some brochures"}', 'C', '', 6),
(551, 'READING','Who most likely is the man?', '{"A": "A flight attendant", "B": "A sales representative", "C": "An event organizer", "D": "A repair technician"}', 'D', '', 7),
(551, 'READING','Why is Sameera unable to attend a meeting?', '{"A": "Her flight was canceled.", "B": "Her car has broken down.", "C": "She is on vacation.", "D": "She is feeling sick."}', 'A', '', 8),
(551, 'READING','What does the woman say the man should do before a meeting?', '{"A": "Read some client information", "B": "Prepare a contract", "C": "Make a dinner reservation", "D": "Check some equipment"}', 'A', '', 9),
(551, 'READING','Where do the speakers work?', '{"A": "At a clothing shop", "B": "At a photography studio", "C": "At a travel agency", "D": "At a furniture store"}', 'C', '', 10),
(551, 'READING','Why does the man say, “Coffee shops need a lot of tables and chairs?"', '{"A": "To request assistance", "B": "To correct an error", "C": "To express disagreement", "D": "To make a guess"}', 'D', '', 11),
(551, 'READING','What will the woman do next?', '{"A": "Process an online order", "B": "Call the building’s property manager", "C": "Meet some new neighbors", "D": "Fix a broken piece of equipment"}', 'B', '', 12),
(551, 'READING','Why does the man apologize?', '{"A": "He used the wrong entrance.", "B": "He is late for an appointment.", "C": "He forgot to bring identification.", "D": "He lost an order number."}', 'B', '', 13),
(551, 'READING','What is the man’s job?', '{"A": "Delivery driver", "B": "Electrician", "C": "Journalist", "D": "Security guard"}', 'D', '', 14),
(551, 'READING','Where does the woman direct the man to go?', '{"A": "To a conference room", "B": "To a security desk", "C": "To a construction site", "D": "To a loading dock"}', 'A', '', 15),
(551, 'READING','Where do the speakers most likely work?', '{"A": "At an advertising agency", "B": "At an electronics shop", "C": "At a furniture store", "D": "At an assembly plant"}', 'A', '', 16),
(551, 'READING','Why does the woman say, "We’ve already sold out"?', '{"A": "To ask for help", "B": "To refuse a request", "C": "To express agreement", "D": "To show concern"}', 'B', '', 17),
(551, 'READING','According to the woman, why is a product popular?', '{"A": "It has good online reviews.", "B": "It has a lifetime warranty.", "C": "It is being advertised by celebrities.", "D": "It is being sold at a low price"}', 'A', '', 18),
(551, 'READING','Why are the men at the store?', '{"A": "To return a defective item", "B": "To purchase a gift", "C": "To publicize a festival", "D": "To apply for a position"}', 'B', '', 19),
(551, 'READING','What hobby is mentioned?', '{"A": "Hiking", "B": "Swimming", "C": "Skiing", "D": "Cycling"}', 'D', '', 20),
(551, 'READING','What does the woman recommend?', '{"A": "Finalizing a schedule", "B": "Consulting a return policy", "C": "Getting a membership", "D": "Downloading a map"}', 'C', '', 21),
(551, 'READING','Why are the speakers traveling?', '{"A": "To attend a conference", "B": "To train some employees", "C": "To meet a client", "D": "To open a new business location"}', 'C', '', 22),
(551, 'READING','What does the man say he will do during the flight?', '{"A": "Update a travel itinerary", "B": "Edit some presentation slides", "C": "Proofread a contract", "D": "Review some resumes"}', 'B', '', 23),
(551, 'READING','What will the speakers most likely do when they land?', '{"A": "Check in to a hotel", "B": "Eat at a restaurant", "C": "Board another flight", "D": "Go to an office building"}', 'A', '', 24),
(551, 'READING','Where most likely are the speakers?', '{"A": "In a computer store", "B": "In a recording studio", "C": "In a medical clinic", "D": "In an electrical supply shop"}', 'D', '', 25),
(551, 'READING','What are the speakers mainly discussing?', '{"A": "A work schedule", "B": "A recent illness", "C": "Some pricing options", "D": "Some maintenance problems"}', 'C', '', 26),
(551, 'READING','What does the woman say the men should do?', '{"A": "Contact a manager", "B": "Complete a form", "C": "Pay a bill", "D": "Provide some identification"}', 'A', '', 27),
(551, 'READING','What type of business do the speakers most likely operate?', '{"A": "A cooking school", "B": "A kitchen supply store", "C": "A dairy farm", "D": "A specialty bakery"}', 'B', '', 28),
(551, 'READING','How does the woman want to reduce expenses?', '{"A": "By relocating a business", "B": "By shortening operating hours", "C": "By using local suppliers", "D": "By purchasing in bulk"}', 'C', '', 29),
(551, 'READING','What is the man concerned about?', '{"A": "A change may affect product quality.", "B": "A new recipe has not been successful.", "C": "An ingredient is no longer being sold.", "D": "A competing business is expanding"}', 'A', '', 30),
(551, 'READING','What are the speakers mainly discussing?', '{"A": "An inspection of a facility", "B": "Transportation of some parts", "C": "A revised government policy", "D": "Some upcoming road construction"}', 'D', '', 31),
(551, 'READING','What does the man say he will do tomorrow?', '{"A": "Calculate a distance", "B": "Adjust a budget", "C": "Talk to local officials", "D": "Print a permit"}', 'C', '', 32),
(551, 'READING','Look at the graphic. According to the speakers, what will be shipped next?', '{"A": "The engine case", "B": "The tower", "C": "The foundation", "D": "The blades"}', 'C', '', 33),
(551, 'READING','What event are the speakers preparing for?', '{"A": "A professional conference", "B": "A political debate", "C": "An awards ceremony", "D": "A musical concert"}', 'A', '', 34),
(551, 'READING','What was the man asked to do?', '{"A": "Collect tickets", "B": "Leave empty rows near the stage", "C": "Set up some extra equipment", "D": "Pass out programs"}', 'C', '', 35),
(551, 'READING','Look at the graphic. Where will the man most likely be working during the event?', '{"A": "At Position 1", "B": "At Position 2", "C": "At Position 3", "D": "At Position 4"}', 'A', '', 36),
(551, 'READING','What does the woman say about the clients?', '{"A": "Their flight was delayed.", "B": "Their contract has not been signed.", "C": "They prefer to try a seafood restaurant.", "D": "They want to visit museums."}', 'C', '', 37),
(551, 'READING','What does the man suggest doing?', '{"A": "Updating an event calendar", "B": "Trying some local food", "C": "Taking a bus tour", "D": "Making reservations"}', 'B', '', 38),
(551, 'READING','Look at the graphic. Which location will the speakers go to?', '{"A": "65 Elm St.", "B": "2 Peach St.", "C": "41 Ames Ave.", "D": "7 Edson Rd."}', 'A', '', 39);

INSERT INTO public.part (part_id, part_name, description, "question_type", instructions, media_id, question_count, order_number, created_at, created_by, updated_at, updated_by)
VALUES(1301, 'Part 13', 'Writing', 'ESSAY'::public."question_type", NULL, NULL, 5, 13, '2025-05-17 17:58:41.866', NULL, NULL, NULL);
INSERT INTO public.section_part (section_id, part_id) VALUES(100350, 1301);
INSERT INTO public.question (grading_type, media_id, part_id, "content", "options", correct_answer, explanation, order_number, created_at, created_by, updated_at, updated_by)
VALUES('OTHER',NULL, 1301, 'In this part of the test, you will write ONE sentence that is based on a picture. With each picture, you will be given TWO words or phrases that you must use in your sentence. You can change the forms of the words and you can use the words in any order.',
       NULL, NULL, NULL, 1, '2025-05-17 18:00:23.089', NULL, NULL, NULL);
